### ISSUE TITLE
incorrect file paths

### ISSUE THREAD

**Issue by gdedi001** [Francy991/prj-rev-bwfs-dasmoto#1]
Currently, all your paths are in absolute format that lead back to your own hard drive. Incidentally, this will only make the project display correctly your own computer. You need to incorporate relative paths instead. Check out this [link](https://www.coffeecup.com/help/articles/absolute-vs-relative-pathslinks/) to learn more. 

https://github.com/Francy991/prj-rev-bwfs-dasmoto/blob/master/DasmotosArts%26Crafts/index.html#L6
 
What you have
`<link href="C:\PROJECTSCodingFra\DasmotosArts&Crafts\resources\CSS\style.css" type="text/css" rel="stylesheet">`

What is should be
`<link href="resources\CSS\style.css" type="text/css" rel="stylesheet">`

**Comment by Francy991** [comment]
Hello, if I use relative paths on my computer (for example in this case where I link the style.css to the html doc) the website doesn't read the style.css so I can't see the graphic modifications on the website when I open it in the browser. 
Everything works only if I write down the absolute path.
How can I solve this problem?

**Comment by gdedi001** [comment]
You should be able to use the following path for your CSS.
```
<link href="./resources/CSS/style.css" type="text/css" rel="stylesheet">
```
