### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by gdedi001** [Francy991/prj-rev-bwfs-dasmoto#4]
_Grade: Needs Improvement_

Good job on your project! You were able to utilize `<div>` tags correctly, and your final submission mimics the design spec based on requirements. In addition to this, you properly implemented the `<strong>` tag to achieve the blue font in your project. An area for improvement here is with your usage of the `class` attribute. In some cases you should have opted for `id` instead. You can find a brief overview of some best practices here: 
https://www.smashingmagazine.com/2008/11/12-principles-for-keeping-your-code-clean/

A recommendation here is to check out the article and make the appropriate changes with respect to `id` and `class`.
https://css-tricks.com/the-difference-between-id-and-class/

**Comment by Francy991** [comment]
Thank you for the review.
I have a question: Do I need to make the changes that you suggested and send back to you the project? 
Or I make the changes without sending back the project to be reviewed? 

And how do I close an "open issue"?

**Comment by gdedi001** [comment]
No, you make those changes on your end for the sake of your personal project improvement. Take the advice I gave and apply it to the next project in your intensive that will be reviewed.
